---
spring:
    profiles: itest

open     jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create-drop
    datasource:
        url: jdbc:mysql://db/nordic?createDatabaseIfNotExist=true
        username: admin
        password: 123456
